name: Build and Release Plugin

on:
    push:
        tags: [ 'v*.*.*' ]
        branches: [ dev-betterDiscord ]


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '16'

            - name: Install dependencies
              run: npm install

            - name: Build plugin
              run: node build-bd.js --ci
            
            - name: Release plugin
              uses: softprops/action-gh-release@v2
              with:
                files: "ServerSorter.plugin.js"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}